{
 "title": "Loki",
 "description": "Monitoring log",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Analytics - CustomerListener",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{application=\"analytics\", level=\"INFO\"} |= `CustomerListener`"
      }
     ]
    },
    {
     "title": "Analytics - Professional Listener",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `ProfessionalListener`"
      }
     ]
    },
    {
     "title": "Analytics - Job Offer Listener",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `JobOfferListener`"
      }
     ]
    },
    {
     "title": "Analytics - Skill Professional Listener",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `SkillProfessionalListener`"
      }
     ]
    },
    {
     "title": "Analytics - Skill Job Offer Listener",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `SkillJobOfferListener`"
      }
     ]
    },
    {
     "title": "Analytics - Customer Controller",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `CustomerController`"
      }
     ]
    },
    {
     "title": "Analytics - Job Offer Controller",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `JobOfferController`"
      }
     ]
    },
    {
     "title": "Analytics - Job Offer State Controller",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `JobOfferStateController`"
      }
     ]
    },
    {
     "title": "Analytics - Professional Controller",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `ProfessionalController`"
      }
     ]
    },
    {
     "title": "Analytics - Skill Controller",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "{application=\"analytics\"} |= `SkillController`"
      }
     ]
    }
   ]
  },
  {
   "title": "Communication Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Communication Manager - Controller",
     "type": "logs",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{application=\"communication-manager\"} |= `CommunicationManagerController`"
      }
     ]
    }
   ]
  },
  { "title": "Crm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CRM - Contact controller",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{application=\"crm\", level=\"INFO\"} |= `ContactController`"
    },
    {}
   ]
  },
  {
   "title": "CRM - Job Offer Controller",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{application=\"crm\", level=\"INFO\"} |= `JobOfferController`"
    }
   ]
  },
  {
   "title": "CRM - Skill Controller",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{application=\"crm\", level!=\"DEBUG\"} |= `SkillController`"
    }
   ]
  },
  {
   "title": "CRM - Contact Service",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{application=\"crm\"} |= `ContactService`"
    }
   ]
  },
  {
   "title": "CRM - Job Offer Service",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{application=\"crm\"} |= `JobOfferService`"
    }
   ]
  },
  {
   "title": "CRM - Skill Service",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{application=\"crm\"} |= `SkillService`"
    }
   ]
  },
  { "title": "Document Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Document Store",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{application=\"document_store\"} |= `DocumentController`"
    }
   ]
  }
 ]
}