{
 "title": "Prometheus",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Analytics - Get",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/analytics/**\",}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Communication Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Communication Manager - Post",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"POST\",outcome=\"SUCCESS\",status=\"204\",uri=\"/communicationmanager/**\",}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CRM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CRM - Get",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/crm/**\",}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CRM - Post",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"POST\",outcome=\"SUCCESS\",status=\"201\",uri=\"/crm/**\",}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CRM - Patch",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"PATCH\",outcome=\"SUCCESS\",status=\"200\",uri=\"/crm/**\",}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CRM - Put",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"PUT\",outcome=\"SUCCESS\",status=\"200\",uri=\"/crm/**\",}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CRM - Delete",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"DELETE\",outcome=\"SUCCESS\",status=\"204\",uri=\"/crm/**\",}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Document Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Document Store - Get",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/documentstore/**\",}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Document Store - Delete",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{error=\"none\",exception=\"none\",method=\"DELETE\",outcome=\"SUCCESS\",status=\"200\",uri=\"/documentstore/**\",}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}