
//@no-log
PUT http://localhost:8080/API/professionals/12/location
Content-Type: application/x-www-form-urlencoded

location=different location

###

//@no-log
PUT http://localhost:8080/API/professionals/12/location
Content-Type: application/x-www-form-urlencoded

###