name: ${PROJECT_NAME}

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grafana_data

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    restart: always
    env_file: .env
    volumes:
      - ./configs/prometheus.yaml/:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    networks:
      - monitoring



  loki:
    pull_policy: always
    image: grafana/loki
    container_name: ${LOKI_CONTAINER_NAME}
    env_file: .env
    volumes:
      - ./configs/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - ${LOKI_PORT}:${LOKI_PORT}
    command: 
      - -config.expand-env=true
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring


  grafana:
    pull_policy: always
    image: grafana/grafana
    container_name: ${GRAFANA_CONTAINER_NAME}
    restart: always
    env_file: .env
    volumes:
      - ./configs/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./configs/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./dashboards/loki_dashboard.json:/var/lib/grafana/dashboards/loki_dashboard.json
      - ./dashboards/prometheus_dashboard.json:/var/lib/grafana/dashboards/prometheus_dashboard.json
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    depends_on:
      - loki
      - prometheus
    networks:
      - monitoring


  promtail:
    pull_policy: always
    image: grafana/promtail
    container_name: ${PROMTAIL_CONTAINER_NAME}
    env_file: .env
    volumes:
      - ../crm/src/log/crm_logfile.log:/var/log/crm_logfile.log
      - ./configs/promtail.yaml:/etc/promtail/promtail.yaml
    ports:
      - ${PROMTAIL_PORT}:${PROMTAIL_PORT}
    depends_on:
      - loki
    command: 
      - -config.expand-env=true
      - -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
