
//@no-log
GET http://localhost:8084/API/analytics/locations

###

//@no-log
GET http://localhost:8084/API/analytics/JobOfferDuration

###

//@no-log
GET http://localhost:8084/API/analytics/JobOfferValue
