spring:
  application:
    name: analytics
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        provider:
          keycloak: #keyclock
            issuer-uri: http://localhost:9090/realms/CRM
            user-name-attribute: sub
        registration:
          CRMclient:
            provider: keycloak
            client-id: apigateway
            client-secret: aXVXpJtABK9M5goNLGsgON8vSLkMIHrt #Luca
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRM

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: analytics
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest


server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework: DEBUG
  file:
    name: './src/log/analytics_logfile.log'