
//@no-log
POST http://localhost:8082/API/joboffers/5
Content-Type: application/json

{
  "description": "a new job offer",
  "requiredSkills": [1,2],
  "duration": 5,
  "notes": "Some note",
  "offerValue": 30000.0
}

###

//@no-log
POST http://localhost:8082/API/joboffers/4
Content-Type: application/json

{
  "description": "Dentista",
  "requiredSkills": [3],
  "duration": 55,
  "notes": "Some note",
  "offerValue": 770.0
}

###
