spring:
  application:
    name: api_gateway
  mvc:
    problemdetails:
      enabled: true
  cloud:
    gateway:
      mvc:
        http-client:
          type: autodetect
        routes:
          #route for document_store
          - id: service_ds
            uri: http://localhost:8081
            predicates:
              - Path= /service_ds/**
            filters:
              - StripPrefix=1
              - TokenRelay
          #route for CRM
          - id: service_crm
            uri: http://localhost:8082
            predicates:
              - Path= /service_crm/**
            filters:
              - StripPrefix=1
              - TokenRelay
          #route for Communication_manager
          - id: service_cm
            uri: http://localhost:8083
            predicates:
              - Path= /service_cm/**
            filters:
              - StripPrefix=1
              - TokenRelay
          #route for analytics
          - id: service_analytics
            uri: http://localhost:8084
            predicates:
              - Path= /service_analytics/**
            filters:
              - StripPrefix=1
              - TokenRelay

          - id: ui
            uri: http://localhost:5173
            predicates:
              - Path=/ui/**
          - id: home
            uri: http://localhost:8080
            predicates:
              - Path=/
            filters:
              - RedirectTo=301, http://localhost:5173
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRM
      client:
        provider:
          keycloak: #keyclock
            issuer-uri: http://localhost:9090/realms/CRM
            user-name-attribute: sub
        registration:
          CRMclient:
            provider: keycloak
            client-id: CRMclient
            client-secret: v2Seb5AyEkjIdEhQs7DjpIZoug1MnbYH #Luca
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/CRMclient

server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG

#spring.security.oauth2.client.provider.keycloak.end-session-endpoint=https://<keycloak-server>/realms/<realm-name>/protocol/openid-connect/logout
#logging:
#  level:
#    org.springframework.security: DEBUG
  #  jpa:
  #    show-sql: true
  #    hibernate:
  #      ddl-auto: update
  #  mvc:
  #    problemdetails:
  #      enabled: true
  #datasource:
  #  url: jdbc:postgresql://postgres:5432/mydatabase
  #  username: myuser
  #  password: secret
  #  driver-class-name: org.postgresql.Driver
