
//@no-log
GET http://localhost:8082/API/contacts

### Add contacts

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Massimo",
  "surname": "Porcheddu",
  "ssn": "MMPP",
  "category": "Unknown",
  "address": ["Via Leonardo"],
  "email": ["massimo@gmail.com"],
  "telephone": ["3881111111"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Luca",
  "surname": "Sturaro",
  "ssn": "LLSS",
  "category": "Unknown",
  "address": ["Via Michelangelo"],
  "email": ["luca@gmail.com"],
  "telephone": ["3882222222"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Miriam",
  "surname": "Ivaldi",
  "ssn": "MMII",
  "category": "Unknown",
  "address": ["Via Raffaello"],
  "email": ["miriam@gmail.com"],
  "telephone": ["3883333333"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Paolo",
  "surname": "Mucilli",
  "ssn": "PPMM",
  "category": "Unknown",
  "address": ["Via Donatello"],
  "email": ["paolo@gmail.com"],
  "telephone": ["3884444444"]
}


### Connect customer

//@no-log
POST http://localhost:8082/API/customers
Content-Type: application/json

{
  "contactId": 3,
  "notes": "Some note"
}

###

POST http://localhost:8082/API/customers
Content-Type: application/json

{
  "contactId": 4,
  "notes": "Some note"
}

### Add skills

//@no-log
POST http://localhost:8082/API/skills
Content-Type: application/json

{
  "skill": "skill_1"
}

###

//@no-log
POST http://localhost:8082/API/skills
Content-Type: application/json

{
  "skill": "skill_2"
}

###

//@no-log
POST http://localhost:8082/API/skills
Content-Type: application/json

{
  "skill": "skill_3"
}

### Add job offer for customer

//@no-log
POST http://localhost:8082/API/joboffers/5
Content-Type: application/json

{
  "description": "Description job 11",
  "requiredSkills": [1, 2, 3],
  "notes": "note job 11",
  "duration": 9.0,
  "offerValue": 55.0
}

###

//@no-log
POST http://localhost:8082/API/joboffers/6
Content-Type: application/json

{
  "description": "Description job 222",
  "requiredSkills": [2, 3],
  "notes": "note job 222",
  "duration": 6.0,
  "offerValue": 59.0
}

###Connect professional

POST http://localhost:8082/API/professionals
Content-Type: application/json

{
  "contactId": 7,
  "geographicalInfo": "Turin",
  "dailyRate": 80.0,
  "notes": "Some note",
  "skills": [1, 2]
}

###

POST http://localhost:8082/API/professionals
Content-Type: application/json

{
  "contactId": 8,
  "geographicalInfo": "Milan",
  "dailyRate": 98.0,
  "notes": "Some note 222",
  "skills": [3, 1]
}

### Add Job Offer professional

//@no-log
POST http://localhost:8082/API/joboffers/7
Content-Type: application/json

{
  "description": "Description job 1",
  "requiredSkills": [1,3],
  "notes": "note job 1",
  "duration": 10.0,
  "offerValue": 70.0
}

###

//@no-log
POST http://localhost:8082/API/joboffers/8
Content-Type: application/json

{
  "description": "Description job 2",
  "requiredSkills": [1,2],
  "notes": "note job 2",
  "duration": 15.0,
  "offerValue": 88.0
}

###

//@no-log
POST http://localhost:8082/API/joboffers/8
Content-Type: application/json

{
  "description": "Description job 3",
  "requiredSkills": [3],
  "notes": "note job 3",
  "duration": 11.0,
  "offerValue": 68.0
}

### Change emplyment state

//@no-log
PUT http://localhost:8082/API/professionals/1/state
Content-Type: application/x-www-form-urlencoded

state=BUSY