
//@no-log
GET http://localhost:8082/API/contacts

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Massimo",
  "surname": "Porcheddu",
  "ssn": "MMPP",
  "category": "Unknown",
  "address": ["Via Leonardo"],
  "email": ["massimo@gmail.com"],
  "telephone": ["3881111111"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Luca",
  "surname": "Sturaro",
  "ssn": "LLSS",
  "category": "Unknown",
  "address": ["Via Michelangelo"],
  "email": ["luca@gmail.com"],
  "telephone": ["3882222222"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Miriam",
  "surname": "Ivaldi",
  "ssn": "MMII",
  "category": "Unknown",
  "address": ["Via Raffaello"],
  "email": ["miriam@gmail.com"],
  "telephone": ["3883333333"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Paolo",
  "surname": "Mucilli",
  "ssn": "PPMM",
  "category": "Unknown",
  "address": ["Via Donatello"],
  "email": ["paolo@gmail.com"],
  "telephone": ["3884444444"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Mario",
  "surname": "Rossi",
  "ssn": "MMRR",
  "category": "Customer",
  "address": ["Via Wario"],
  "email": ["mario@gmail.com"],
  "telephone": ["3885555555"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Luigi",
  "surname": "Verdi",
  "ssn": "LLVV",
  "category": "Customer",
  "address": ["Via Wluigi"],
  "email": ["luigi@gmail.com"],
  "telephone": ["3886666666"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Steve",
  "surname": "Jobs",
  "ssn": "SSJJ",
  "category": "Professional",
  "address": ["Via Cupertino"],
  "email": ["steve@gmail.com"],
  "telephone": ["3887777777"]
}

###

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Bill",
  "surname": "Gates",
  "ssn": "BBGG",
  "category": "Professional",
  "address": ["Via Window"],
  "email": ["bill@gmail.com"],
  "telephone": ["3889999999"]
}
