
//@no-log
GET http://localhost:8082/API/joboffers

### Add contacts

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Luca",
  "surname": "Sturaro",
  "ssn": "LLSS7",
  "category": "Unknown",
  "address": ["Via Michelangelo"],
  "email": ["luca@gmail.com"],
  "telephone": ["3882222222"]
}

### Add customer

//@no-log
POST http://localhost:8082/API/customers
Content-Type: application/json

{
  "contactId": 2,
  "notes": "Some note"
}

### check existing skills

//@no-log
GET http://localhost:8082/API/skills

### Add skills

//@no-log
POST http://localhost:8082/API/skills
Content-Type: application/json

{
  "skill": "skill_4"
}

### Add job offer for customer

//@no-log
POST http://localhost:8082/API/joboffers/1
Content-Type: application/json

{
  "description": "Description job 2",
  "requiredSkills": [1, 2],
  "notes": "note job 11",
  "duration": 9.0,
  "offerValue": 55.0
}

### check existing contacts to make into professionals

//@no-log
GET http://localhost:8082/API/contacts

###Connect professional

//@no-log
POST http://localhost:8082/API/professionals
Content-Type: application/json

{
  "contactId": 6,
  "geographicalInfo": "Turin",
  "dailyRate": 80.0,
  "notes": "Some note",
  "skills": [1]
}

###

//@no-log
POST http://localhost:8082/API/professionals
Content-Type: application/json

{
"contactId": 8,
"geographicalInfo": "Milan",
"dailyRate": 80.0,
"notes": "Some note",
"skills": [1]
}

### Change emplyment state

//@no-log
PUT http://localhost:8082/API/professionals/1/state
Content-Type: application/x-www-form-urlencoded

state=BUSY





