### Get contacts

//@no-log
GET http://localhost:8082/API/contacts

### Add contacts

//@no-log
POST http://localhost:8082/API/contacts
Content-Type: application/json

{
  "name": "Luca",
  "surname": "Sturaro",
  "ssn": "LLSS22",
  "category": "Unknown",
  "address": ["Via Michelangelo"],
  "email": ["luca@gmail.com"],
  "telephone": ["3882222222"]
}

### Add customer

//@no-log
POST http://localhost:8082/API/customers
Content-Type: application/json

{
  "contactId": 52,
  "notes": "Some note"
}

### check existing skills

//@no-log
GET http://localhost:8082/API/skills

### Add skills

//@no-log
POST http://localhost:8082/API/skills
Content-Type: application/json

{
  "skill": "skill_4"
}

### check existing job offers

//@no-log
GET http://localhost:8082/API/joboffers/

### Add job offer for customer

//@no-log
POST http://localhost:8082/API/joboffers/52
Content-Type: application/json

{
  "description": "Description job 2",
  "requiredSkills": [1, 2, 3],
  "notes": "note job 11",
  "duration": 12.0,
  "offerValue": 100.0
}

### check existing contacts to make into professionals

//@no-log
GET http://localhost:8082/API/contacts

### Connect professional 1

//@no-log
POST http://localhost:8082/API/professionals
Content-Type: application/json

{
  "contactId": 113,
  "geographicalInfo": "Turin",
  "dailyRate": 80.0,
  "notes": "Some note",
  "skills": [2]
}

### Connect professional 2

//@no-log
POST http://localhost:8082/API/professionals
Content-Type: application/json

{
"contactId": 114,
"geographicalInfo": "Milan",
"dailyRate": 295.0,
"notes": "Some note",
"skills": [1, 2, 3]
}

### Change emplyment state

//@no-log
PUT http://localhost:8082/API/professionals/1/state
Content-Type: application/x-www-form-urlencoded

state=BUSY





